// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Smartframe)
QT_DECLARE_EXTERN_RESOURCE(qmake_Smartframe)
QT_DECLARE_EXTERN_RESOURCE(Smartframe_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Smartframe)

class SmartframePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    SmartframePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Smartframe)
QT_KEEP_RESOURCE(qmlcache_Smartframe)
QT_KEEP_RESOURCE(qmake_Smartframe)
QT_KEEP_RESOURCE(Smartframe_raw_qml_0)
    }
};



#include "Smartframeplugin_SmartframePlugin.moc"
